SR/adventures/config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :states
  get 'welcome/index'

  get 'welcome/about'

  get 'ilovetocode' => 'welcome#index'

  get 'home' => 'welcome#index'

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SR/adventures/app/models/activity.rb
class Activity < ApplicationRecord
end

SR/adventures/app/models/state.rb
class State < ApplicationRecord
end

SR/adventures/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :cost, :duration)
    end
end

SR/adventures/app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :capital, :population)
    end
end

SR/adventures/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

SR/adventures/app/helpers/activities_helper.rb
module ActivitiesHelper
end

SR/adventures/app/helpers/states_helper.rb
module StatesHelper
end

SR/adventures/app/views/states/_form.html.erb
<div class="star">
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <br>
    <%= form.text_field :name, id: :state_name %>
  </div>

  <div class="field">
    <%= form.label :capital %>
    <br>
    <%= form.text_field :capital, id: :state_capital %>
  </div>

  <div class="field">
    <%= form.label :population %>
    <br>
    <%= form.number_field :population, id: :state_population %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

SR/adventures/app/views/states/edit.html.erb
<div class="formstar">

<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

</div>

SR/adventures/app/views/states/index.html.erb
<div class="formstar">

<p id="notice"><%= notice %></p>

<h1>States</h1>

<div class="tablestar">
<div style="overflow-x:auto;">
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Capital</th>
      <th>Population</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.id %></td>
        <td><%= state.name %></td>
        <td><%= state.capital %></td>
        <td><%= state.population %></td>
        <td><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> <%= link_to 'Show', state %></td>
        <td><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_state_path(state) %></td>
        <td><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span> <%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New State', new_state_path %></button>

</div>

SR/adventures/app/views/states/new.html.erb
<div class="formstar">

<h1>New State</h1>

<div class="divstar"
<%= render 'form', state: @state %>

<span class="glyphicon glyphicon-backward" aria-hidden="true"></span> <%= link_to 'Back', states_path %>
</div>
</div>

SR/adventures/app/views/states/show.html.erb
<div class="formstar">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Capital:</strong>
  <%= @state.capital %>
</p>

<p>
  <strong>Population:</strong>
  <%= @state.population %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>
</div>

SR/adventures/app/views/welcome/about.html.erb
<div class="container" id="container_about">
<div class="divabout"> 
<h1>About</h1>

<p>Lorem ipsum dolor sit amet, te quo atqui mazim postea. 
Enim congue ei nam, ex commodo consectetuer mea. 
Mei error commune perfecto id, esse erant omnium est no. 
Id eam modus sonet meliore, accumsan iracundia his at. 
Quo id quot novum, per cu postea expetenda, eu brute fugit est. 
Usu option interpretaris no, ex accumsan invidunt voluptaria pro.</p>

<p>Vix ad ceteros intellegat, id per nulla ornatus. 
Est ea tacimates corrumpit sadipscing. Duis imperdiet te pro. 
Veri illud reformidans id nec, eu vix vidit petentium. Nam unum possim quaestio ei.</p>
<div style="margin-top: 50px">
<div class="btn-group btn-group-justified" role="group" aria-label="...">
<div class="btn-group" role="group">
  <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Enter User Name</button>
</div>
<div class="btn-group" role="group">
  <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Add User Data</button>
</div>
<div class="btn-group" role="group">
  <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Leave User Comments</button>
</div>
</div>
</div>
</div>
</div>

SR/adventures/app/views/welcome/index.html.erb
<div class="container" id="container_home">
<div class="col-md-6">
<div class="shoutout">
  <div class="body" style="margin-top: 100px">
    <p class="shout">Lorem ipsum dolor sit amet, te quo atqui mazim postea...</p>
    <p class="author">by JOLT.<span class="glyphicon glyphicon-flash" aria-hidden="true"></span> enthusiast</p>
    <p class="date">Oct 22, 2017 @ 5:00PM</p>
  </div>
  <div class="arrow"><button type="button" class="btn btn-success">LEARN MORE NOW <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></button></div>
  <div class="shadow"></div>
</div>
</div>
</div>