taylor_scaffold/config/routes.rb
Rails.application.routes.draw do
  resources :lakes
  resources :mountains
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

taylor_scaffold/app/models/lake.rb
class Lake < ApplicationRecord
end

taylor_scaffold/app/models/mountain.rb
class Mountain < ApplicationRecord
    validates :name, presence: true
end

taylor_scaffold/app/controllers/lakes_controller.rb
class LakesController < ApplicationController
  before_action :set_lake, only: [:show, :edit, :update, :destroy]

  # GET /lakes
  # GET /lakes.json
  def index
    @lakes = Lake.all
  end

  # GET /lakes/1
  # GET /lakes/1.json
  def show
  end

  # GET /lakes/new
  def new
    @lake = Lake.new
  end

  # GET /lakes/1/edit
  def edit
  end

  # POST /lakes
  # POST /lakes.json
  def create
    @lake = Lake.new(lake_params)

    respond_to do |format|
      if @lake.save
        format.html { redirect_to @lake, notice: 'Lake was successfully created.' }
        format.json { render :show, status: :created, location: @lake }
      else
        format.html { render :new }
        format.json { render json: @lake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lakes/1
  # PATCH/PUT /lakes/1.json
  def update
    respond_to do |format|
      if @lake.update(lake_params)
        format.html { redirect_to @lake, notice: 'Lake was successfully updated.' }
        format.json { render :show, status: :ok, location: @lake }
      else
        format.html { render :edit }
        format.json { render json: @lake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lakes/1
  # DELETE /lakes/1.json
  def destroy
    @lake.destroy
    respond_to do |format|
      format.html { redirect_to lakes_url, notice: 'Lake was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lake
      @lake = Lake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lake_params
      params.require(:lake).permit(:name, :depth, :circumference, :location)
    end
end

taylor_scaffold/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  before_action :set_mountain, only: [:show, :edit, :update, :destroy]

  # GET /mountains
  # GET /mountains.json
  def index
    @mountains = Mountain.all
  end

  # GET /mountains/1
  # GET /mountains/1.json
  def show
  end

  # GET /mountains/new
  def new
    @mountain = Mountain.new
  end

  # GET /mountains/1/edit
  def edit
  end

  # POST /mountains
  # POST /mountains.json
  def create
    @mountain = Mountain.new(mountain_params)

    respond_to do |format|
      if @mountain.save
        format.html { redirect_to @mountain, notice: 'Mountain was successfully created.' }
        format.json { render :show, status: :created, location: @mountain }
      else
        format.html { render :new }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mountains/1
  # PATCH/PUT /mountains/1.json
  def update
    respond_to do |format|
      if @mountain.update(mountain_params)
        format.html { redirect_to @mountain, notice: 'Mountain was successfully updated.' }
        format.json { render :show, status: :ok, location: @mountain }
      else
        format.html { render :edit }
        format.json { render json: @mountain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mountains/1
  # DELETE /mountains/1.json
  def destroy
    @mountain.destroy
    respond_to do |format|
      format.html { redirect_to mountains_url, notice: 'Mountain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mountain
      @mountain = Mountain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mountain_params
      params.require(:mountain).permit(:name, :height, :circumference, :location)
    end
end

taylor_scaffold/app/helpers/lakes_helper.rb
module LakesHelper
end

taylor_scaffold/app/helpers/mountains_helper.rb
module MountainsHelper
end

taylor_scaffold/app/views/mountains/_form.html.erb
<%= form_with(model: mountain, local: true) do |form| %>
  <% if mountain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mountain.errors.count, "error") %> prohibited this mountain from being saved:</h2>

      <ul>
      <% mountain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :mountain_name %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height, id: :mountain_height %>
  </div>

  <div class="field">
    <%= form.label :circumference %>
    <%= form.number_field :circumference, id: :mountain_circumference %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :mountain_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

taylor_scaffold/app/views/mountains/edit.html.erb
<h1>Editing Mountain</h1>

<%= render 'form', mountain: @mountain %>

<%= link_to 'Show', @mountain %> |
<%= link_to 'Back', mountains_path %>

taylor_scaffold/app/views/mountains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mountains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Circumference</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mountains.each do |mountain| %>
      <tr>
        <td><%= mountain.name %></td>
        <td><%= mountain.height %></td>
        <td><%= mountain.circumference %></td>
        <td><%= mountain.location %></td>
        <td><%= link_to 'Show', mountain %></td>
        <td><%= link_to 'Edit', edit_mountain_path(mountain) %></td>
        <td><%= link_to 'Destroy', mountain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mountain', new_mountain_path %>

taylor_scaffold/app/views/mountains/new.html.erb
<h1>New Mountain</h1>

<%= render 'form', mountain: @mountain %>

<%= link_to 'Back', mountains_path %>

taylor_scaffold/app/views/mountains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mountain.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @mountain.height %>
</p>

<p>
  <strong>Circumference:</strong>
  <%= @mountain.circumference %>
</p>

<p>
  <strong>Location:</strong>
  <%= @mountain.location %>
</p>

<%= link_to 'Edit', edit_mountain_path(@mountain) %> |
<%= link_to 'Back', mountains_path %>